runtime: java11
env: flex

  
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling: 
  instances: 1
  
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
  JETTY_MODULES_ENABLE: websocket
#network:
#  forwarded_ports:
#  - 65080
#  instance_tag: websocket
#  session_affinity: true
#automatic_scaling:
#  max_instances: 1 # 
#  min_instances: 0 # 
#  target_cpu_utilization: 0.95 
#  max_concurrent_requests: 80 

#env_variables:
#  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
#  
#beta_settings: cloud_sql_instances:learned-tube-276404:asia-northeast3:game-demo-db=tcp:3306