runtime: java11

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
network:
  session_affinity: true
  
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling: 
  instances: 1
#automatic_scaling:
#  max_instances: 1 # 
#  min_instances: 0 # 
#  target_cpu_utilization: 0.95 
#  max_concurrent_requests: 80 

#env_variables:
#  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
#  
#beta_settings: cloud_sql_instances:learned-tube-276404:asia-northeast3:game-demo-db=tcp:3306