spring:
  cloud:
    gcp:
      sql:
        database-name: gamedb
        instance-connection-name: learned-tube-276404:asia-northeast3:game-demo-db
  datasource:
    username: root
    password: NGqsPBsg10v2DHLa
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/studydb?serverTimezone=Asia/Seoul
#    username: study
#    password: study

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#      
#  messages:
#    basename: i18n/exception
#    encoding: UTF-8